### PR TITLE
New Delegate Methods on WLRemoteLink

### PR DESCRIPTION
**Pull request by milestinsley**
I needed this feature for our app and thought it would be a useful addition to the framework.

The need arose when I wanted my session controller to know whenever a Ratatosk persistence action finished or failed.

This update simply lets you set a `delegate` on the shared `WLRemoteLink object` i.e.:

```
[[WLRemoteLink sharedRemoteLink] setDelegate:self];
```

The delegate will then receive the following messages:

_\- (void)remoteActionDidFail:(WLRemoteAction)anAction dueToAuthentication:(BOOL)dueToAuthentication_

_\- (void)remoteActionDidFinish:(WLRemoteAction)anAction_

### CODE REVIEW

**Comment by aljungberg** [comment]
Looks nice. Wouldn't observing `WLRemoteLink`'s state allow you to see when it's in `WLRemoteLinkStateAuthenticationError` or `WLRemoteLinkStateRequestFailureError`?

**Comment by milestinsley** [comment]
Observing changes to `WLRemoteLinks`'s state was my original thought, but the state won't change on every action.

I specifically needed to know **every** time an action was finished, even if the state is already `WLRemoteLinkStateNormal` (and doesn't change).

**Comment by milestinsley** [comment]
Ok, I understand what you mean now. At first it appeared that observing `WLRemoteLinks`'s state would _only_ trigger when it actually _changes_ state. But I've been playing around with it and as you suggest, the observer does in fact fire whenever the state is set internally, regardless of if it has _changed_ or not. 

This is just what I needed! Thanks for your help. I'll close this PR.

**Comment by aljungberg** [comment]
Actually it might not be a bad pull request either way. I was planning to merge it. :)

**Pull request closed without merging**
